FROM amd64/python:3.7-slim-buster

WORKDIR /app

COPY requirements.txt ./
RUN pip install -r requirements.txt

RUN apt update && apt install -y libglib2.0-0 libsm6 libxext6 libxrender1

COPY . .

CMD [ "python3", "-u", "./mainv2.py" ]